### ISSUE TITLE
Qwiic_BME280_CCS811_Combo for python?

### ISSUE THREAD

**Issue by wolli1234** [sparkfun/Qwiic_BME280_CCS811_Combo#12]
Hello,

I'm trying to read BME280 humidity and temperature data to integrate it into CO2 calculation in the CCS811 sensor. I can run the Qwiic_CCS811_Py module and Qwiic_BME280_Py  module separately but I'm not getting how to send the data from one sensor to the other. 

Can you give me a hint how to accomplish that in python? Is there a Qwiic_BME280_CCS811_Combo module for python?

Best regards,
Wolli

**Comment by santaimpersonator** [comment]
Please refer to the `set_environmental_data()` method in the [API documentation of the CCS811 Python package](https://qwiic-ccs811-py.readthedocs.io/en/latest/apiref.html#qwiic_ccs811.QwiicCcs811.set_environmental_data)

Since this issue has nothing to do with the hardware, I am transferring this issue to the GitHub repository for the CCS811 Python package. I am also closing the issue since it is addressed in the documentation (linked above).
